### ISSUE TITLE
Could not reconnect to vCenter

### ISSUE THREAD

**Issue by cblomart** [cblomart/vsphere-graphite#1]
vsphere-graphite: 2016/03/26 13:42:02 Could not connect to vcenter:  vcenter2.contoso.local
vsphere-graphite: 2016/03/26 13:42:02 Error:  ServerFaultCode: Cannot complete login due to an incorrect user name or password.
vsphere-graphite: 2016/03/26 13:42:02 Could not connect to vcenter:  drsvmvixvcp01.finbel.intra
vsphere-graphite: 2016/03/26 13:42:02 Error:  ServerFaultCode: Cannot complete login due to an incorrect user name or password.
vsphere-graphite: panic: runtime error: invalid memory address or nil pointer dereference
vsphere-graphite: [signal 0xb code=0x1 addr=0x0 pc=0x4c9f81]
vsphere-graphite: goroutine 211868 [running]:
vsphere-graphite: github.com/vmware/govmomi.(*Client).Logout(0x0, 0x7f963f65b198, 0xc208187700, 0x0, 0x0)
vsphere-graphite: /root/gopath/src/github.com/vmware/govmomi/client.go:140 +0x31
vsphere-graphite: main.(*VCenter).Query(0xc20871e370, 0xc20800c7e0, 0x2, 0x4, 0xc20812a000, 0x3, 0x4, 0x3c, 0xc20800abb0, 0xd, ...)
vsphere-graphite: /root/vsphere-graphite/vsphere-graphite.go:180 +0x55e

**Comment by cblomart** [comment]
Apparently this was because of defering vsphere logout just after login... Without checking for error.
