### ISSUE TITLE
Invalid memory address using InfluxDB Backend

### ISSUE THREAD

**Issue by SpencerCornish** [cblomart/vsphere-graphite#5]
I am receiving an error when I try to push data to InfluxDB.  Not sure if it is me configuring things improperly, or if it is an issue with the script itself.
Here is the output I am getting when I try to run this:

```
[spencer@V-Influx ~]$ $GOBIN/vsphere-graphite
2017/03/01 14:08:53 Starting daemon: vsphere-graphite
2017/03/01 14:08:53 connecting to vcenter: vesxi.home
2017/03/01 14:08:53 Appended metric group with cpu.usage.average identified by 1 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric group with cpu.usage.average identified by 1 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric cpu.usage.maximum identified by 2 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric cpu.usage.maximum identified by 2 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric cpu.usagemhz.average identified by 5 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric cpu.usagemhz.average identified by 5 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric cpu.usagemhz.maximum identified by 6 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric cpu.usagemhz.maximum identified by 6 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric cpu.totalCapacity.average identified by 23 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric cpu.totalCapacity.average identified by 23 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric mem.usage.average identified by 65537 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric mem.usage.average identified by 65537 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric mem.usage.maximum identified by 65538 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric mem.usage.maximum identified by 65538 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric mem.active.average identified by 65545 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric mem.active.average identified by 65545 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric mem.active.maximum identified by 65546 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric mem.active.maximum identified by 65546 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric mem.vmmemctl.average identified by 65582 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric mem.vmmemctl.average identified by 65582 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric mem.vmmemctl.maximum identified by 65583 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric mem.vmmemctl.maximum identified by 65583 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric mem.consumed.average identified by 65611 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric mem.consumed.average identified by 65611 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric mem.consumed.maximum identified by 65612 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric mem.consumed.maximum identified by 65612 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric mem.totalCapacity.average identified by 65625 to vcenter vesxi.home for VirtualMachine
2017/03/01 14:08:53 Appended metric mem.totalCapacity.average identified by 65625 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric disk.maxTotalLatency.latest identified by 131095 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric disk.numberReadAveraged.average identified by 131097 to vcenter vesxi.home for HostSystem
2017/03/01 14:08:53 Appended metric disk.numberWriteAveraged.average identified by 131098 to vcenter vesxi.home for HostSystem
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x486d0f]

goroutine 1 [running]:
panic(0xa8f480, 0xc42000c0c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
log.(*Logger).Output(0x0, 0x2, 0xc4203502e0, 0x12, 0x0, 0x0)
        /usr/local/go/src/log/log.go:147 +0x6f
log.(*Logger).Println(0x0, 0xc4202bf858, 0x1, 0x1)
        /usr/local/go/src/log/log.go:182 +0x6a
github.com/cblomart/vsphere-graphite/backend.(*Backend).Init(0xc4200d6108, 0xc420058820, 0xc420058870, 0x4, 0xc420058820)
        /home/spencer/projects/src/src/github.com/cblomart/vsphere-graphite/backend/backend.go:77 +0x15c
main.(*Service).Manage(0xc4202bfe78, 0x0, 0x0, 0x0, 0x0)
        /home/spencer/projects/src/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:117 +0x569
main.main()
        /home/spencer/projects/src/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:176 +0x10f
```

And here is my config file:

```
`{
  "Domain": ".home",
  "Interval": 60,
  "VCenters": [
    { "Username": "********", "Password": "************", "Hostname": `"******.home"` }
  ],
  "Influxdb": {
    "Hostname": "v-*****.home",
    "Port": 8086,
    "Username": "****",
    "Password": "***********",
    "Database": "vmware_performance"

  },
  "Metrics": [
    {
      "ObjectType": [ "VirtualMachine", "HostSystem" ],
      "Definition": [
        { "Metric": "cpu.usage.average", "Instances": "" },
        { "Metric": "cpu.usage.maximum", "Instances": "" },
        { "Metric": "cpu.usagemhz.average", "Instances": "" },
        { "Metric": "cpu.usagemhz.maximum", "Instances": "" },
        { "Metric": "cpu.totalCapacity.average", "Instances": "" },
        { "Metric": "mem.usage.average", "Instances": "" },
        { "Metric": "mem.usage.maximum", "Instances": "" },
        { "Metric": "mem.consumed.average", "Instances": "" },
        { "Metric": "mem.consumed.maximum", "Instances": "" },
        { "Metric": "mem.active.average", "Instances": "" },
        { "Metric": "mem.active.maximum", "Instances": "" },
        { "Metric": "mem.vmmemctl.average", "Instances": "" },
        { "Metric": "mem.vmmemctl.maximum", "Instances": "" },
        { "Metric": "mem.totalCapacity.average", "Instances": "" }
      ]
    },
    {
      "ObjectType": [ "HostSystem" ],
      "Definition": [
        { "Metric": "disk.maxTotalLatency.latest", "Instances": "" },
        { "Metric": "disk.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "disk.numberWriteAveraged.average", "Instances": "*" }
      ]
    }
  ]
}
```
Please let me know if there is anything else I can provide!  I am also happy to help with any other influx-related testing.

-Spencer

**Comment by cblomart** [comment]
might trywith this config:

```
`{
  "Domain": ".home",
  "Interval": 60,
  "VCenters": [
    { "Username": "********", "Password": "************", "Hostname": `"******.home"` }
  ],
  "Backend": {
    "Type": "influxdb",
    "Hostname": "v-*****.home",
    "Port": 8086,
    "Username": "****",
    "Password": "***********",
    "Database": "vmware_performance"

  },
  "Metrics": [
    {
      "ObjectType": [ "VirtualMachine", "HostSystem" ],
      "Definition": [
        { "Metric": "cpu.usage.average", "Instances": "" },
        { "Metric": "cpu.usage.maximum", "Instances": "" },
        { "Metric": "cpu.usagemhz.average", "Instances": "" },
        { "Metric": "cpu.usagemhz.maximum", "Instances": "" },
        { "Metric": "cpu.totalCapacity.average", "Instances": "" },
        { "Metric": "mem.usage.average", "Instances": "" },
        { "Metric": "mem.usage.maximum", "Instances": "" },
        { "Metric": "mem.consumed.average", "Instances": "" },
        { "Metric": "mem.consumed.maximum", "Instances": "" },
        { "Metric": "mem.active.average", "Instances": "" },
        { "Metric": "mem.active.maximum", "Instances": "" },
        { "Metric": "mem.vmmemctl.average", "Instances": "" },
        { "Metric": "mem.vmmemctl.maximum", "Instances": "" },
        { "Metric": "mem.totalCapacity.average", "Instances": "" }
      ]
    },
    {
      "ObjectType": [ "HostSystem" ],
      "Definition": [
        { "Metric": "disk.maxTotalLatency.latest", "Instances": "" },
        { "Metric": "disk.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "disk.numberWriteAveraged.average", "Instances": "*" }
      ]
    }
  ]
}
```

**Comment by cblomart** [comment]
@SpencerCornish, did you have time to test the proposed config changes ?

**Comment by cblomart** [comment]
no... no datastores yet... i do base the stats on realtime collection. vmware doesn't have or doesn't expose realtime data about datastores.

they are available at a lower collection interval... then we would need to manage multiple collection interval from vmware and from vpshere-graphite.

realtime interval: 20s
next interval: 5mins

what you could now do with influx is query and aggregate stats about one datastore (tags)

**Comment by cblomart** [comment]
@SpencerCornish, i'll close this issue on monday. If you still have an issue... don't hesitate.

**Comment by cblomart** [comment]
Closing without feedback. 
Hope it works for @SpencerCornish

**Comment by Papalloon** [comment]
Had the same issue, your solution work perfectly well. Thank you!
