### ISSUE TITLE
Race condition with multiple vSpheres

### ISSUE THREAD

**Issue by jlothian** [cblomart/vsphere-graphite#51]
when running against multiple vspheres from a single vsphere-graphite instance, there appears to be a race condition:

```
2018/07/24 19:29:16 removing mor from string map: vm-74
2018/07/24 19:29:16 removing mor from string map: host-21
2018/07/24 19:29:16 removing mor from string map: host-13
2018/07/24 19:29:16 removing mor from string map: vm-24
2018/07/24 19:29:16 removing mor from string map: vm-81
fatal error: concurrent map writes

goroutine 1044 [running]:
runtime.throw(0x15a33ee, 0x15)
	/usr/lib/go-1.10/src/runtime/panic.go:616 +0x81 fp=0xc420c71e40 sp=0xc420c71e20 pc=0x431261
runtime.mapdelete_faststr(0x1364780, 0xc4205a2120, 0xc420ac989b, 0x5)
	/usr/lib/go-1.10/src/runtime/hashmap_fast.go:892 +0x386 fp=0xc420c71eb0 sp=0xc420c71e40 pc=0x40fbe6
github.com/cblomart/vsphere-graphite/utils.CleanStringMap(0xc4205a2120, 0xc4200dce00, 0x6a, 0x70)
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/utils/utils.go:286 +0x27e fp=0xc420c71fa8 sp=0xc420c71eb0 pc=0xf1c14e
github.com/cblomart/vsphere-graphite/vsphere.(*VCenter).Query(0xc420c73f10, 0x1e, 0xc4200b2b80, 0x13, 0xc4200aa680, 0xa, 0x10, 0xc42000e058, 0xc42000e068)
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/vsphere/vsphere.go:450 +0x4b4b fp=0xc420c73eb8 sp=0xc420c71fa8 pc=0x106fa9b
main.queryVCenter(0xc4200ac4e0, 0x22, 0xc4200b2bc0, 0x1b, 0xc4200b11c0, 0x9, 0xc42001fa30, 0x2, 0x2, 0xc420122da0, ...)
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:47 +0xa5 fp=0xc420c73f10 sp=0xc420c73eb8 pc=0x10bf955
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420c73f18 sp=0xc420c73f10 pc=0x461f71
created by main.(*Service).Manage
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:211 +0x2205

goroutine 1 [select]:
main.(*Service).Manage(0xc420257e98, 0x0, 0x0, 0x0, 0x0)
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:185 +0x15d3
main.main()
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:280 +0x33a

```

I've also noticed that the metrics that end up in elasticsearch are incorrect.  I will get metrics for VMs that are in vsphere2 associated with vsphere1.  It looks like what's happening is that right now there are global maps, and all the vspheres try to use them concurrently, instead of having a map per vsphere?

**Comment by cblomart** [comment]
I added a global cache and used locks to prevent race conditions.
